import React from 'react';
import {
  Armchair,
  AudioWaveform,
  BarChart3,
  Blocks,
  BookOpen,
  Bot,
  Box,
  Brain,
  Bug,
  Calculator,
  Calendar,
  Camera,
  Car,
  ChefHat,
  Clapperboard,
  ClipboardList,
  Cloud,
  Code,
  Construction,
  Database,
  Disc,
  Droplet,
  Dumbbell,
  FileAudio,
  FileText,
  FileUser,
  Flame,
  FlaskConical,
  Flower2,
  Gamepad2,
  Globe,
  GraduationCap,
  Hammer,
  Headphones,
  Home,
  Image,
  Keyboard,
  Languages,
  Layout,
  LifeBuoy,
  Link,
  Mail,
  Megaphone,
  MessageSquare,
  Mic,
  Music,
  Package,
  Paintbrush,
  Palette,
  PenTool,
  Pencil,
  Plug,
  Podcast,
  Presentation,
  Search,
  Server,
  Shapes,
  Share2,
  Shield,
  Shirt,
  Smartphone,
  Sparkles,
  SpellCheck,
  Thermometer,
  Wrench as ToolIcon,
  Truck,
  Utensils,
  Video,
  Wand2,
  Wrench,
  Zap,
  Circle,
  LucideIcon,
} from 'lucide-react';

// Static map of skill icons - tree-shakeable alternative to dynamicIconImports
const SKILL_ICONS: Record<string, LucideIcon> = {
  'armchair': Armchair,
  'audio-waveform': AudioWaveform,
  'bar-chart-3': BarChart3,
  'blocks': Blocks,
  'book-open': BookOpen,
  'bot': Bot,
  'box': Box,
  'brain': Brain,
  'bug': Bug,
  'calculator': Calculator,
  'calendar': Calendar,
  'camera': Camera,
  'car': Car,
  'chef-hat': ChefHat,
  'clapperboard': Clapperboard,
  'clipboard-list': ClipboardList,
  'cloud': Cloud,
  'code': Code,
  'construction': Construction,
  'database': Database,
  'disc': Disc,
  'droplet': Droplet,
  'dumbbell': Dumbbell,
  'file-audio': FileAudio,
  'file-text': FileText,
  'file-user': FileUser,
  'flame': Flame,
  'flask-conical': FlaskConical,
  'flower-2': Flower2,
  'gamepad-2': Gamepad2,
  'globe': Globe,
  'graduation-cap': GraduationCap,
  'hammer': Hammer,
  'headphones': Headphones,
  'home': Home,
  'image': Image,
  'keyboard': Keyboard,
  'languages': Languages,
  'layout': Layout,
  'life-buoy': LifeBuoy,
  'link': Link,
  'mail': Mail,
  'megaphone': Megaphone,
  'message-square': MessageSquare,
  'mic': Mic,
  'music': Music,
  'package': Package,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'pen-tool': PenTool,
  'pencil': Pencil,
  'plug': Plug,
  'podcast': Podcast,
  'presentation': Presentation,
  'search': Search,
  'server': Server,
  'shapes': Shapes,
  'share-2': Share2,
  'shield': Shield,
  'shirt': Shirt,
  'smartphone': Smartphone,
  'sparkles': Sparkles,
  'spell-check': SpellCheck,
  'thermometer': Thermometer,
  'tool': ToolIcon,
  'truck': Truck,
  'utensils': Utensils,
  'video': Video,
  'wand-2': Wand2,
  'wrench': Wrench,
  'zap': Zap,
};

interface SkillIconProps extends React.ComponentProps<LucideIcon> {
  name: string;
}

export const SkillIcon: React.FC<SkillIconProps> = ({ name, ...props }) => {
  const IconComponent = SKILL_ICONS[name] || Circle;
  return <IconComponent {...props} />;
};

export default SkillIcon;
