-- Add icon column if not exists and update all skills with icons
ALTER TABLE public.skills ADD COLUMN IF NOT EXISTS icon text;

-- Update icons for all skills
UPDATE public.skills SET icon = CASE name
  -- Creative & Design
  WHEN 'Video Editing' THEN 'video'
  WHEN 'Graphic Design' THEN 'palette'
  WHEN 'Animation (2D/3D)' THEN 'clapperboard'
  WHEN 'Motion Graphics' THEN 'sparkles'
  WHEN 'Audio Engineering' THEN 'audio-waveform'
  WHEN 'Music Production' THEN 'music'
  WHEN 'Voice Over' THEN 'mic'
  WHEN 'Photography' THEN 'camera'
  WHEN 'Videography' THEN 'video'
  WHEN 'Illustration' THEN 'pen-tool'
  WHEN 'Logo Design' THEN 'shapes'
  WHEN 'Thumbnail Design' THEN 'image'
  WHEN 'Podcast Editing' THEN 'podcast'
  WHEN 'VFX/Visual Effects' THEN 'wand-2'
  WHEN '3D Modeling' THEN 'box'
  WHEN 'UI/UX Design' THEN 'layout'
  WHEN 'Interior Design' THEN 'home'
  WHEN 'Fashion Design' THEN 'shirt'
  -- Tech & Digital
  WHEN 'Web Development' THEN 'globe'
  WHEN 'Mobile App Development' THEN 'smartphone'
  WHEN 'AI/ML Development' THEN 'brain'
  WHEN 'Data Science' THEN 'bar-chart-3'
  WHEN 'Cybersecurity' THEN 'shield'
  WHEN 'Cloud Computing' THEN 'cloud'
  WHEN 'DevOps' THEN 'server'
  WHEN 'Database Administration' THEN 'database'
  WHEN 'API Development' THEN 'plug'
  WHEN 'Blockchain Development' THEN 'link'
  WHEN 'Game Development' THEN 'gamepad-2'
  WHEN 'Software Testing/QA' THEN 'bug'
  WHEN 'AI Automation' THEN 'bot'
  WHEN 'Chatbot Development' THEN 'message-square'
  WHEN 'Data Entry' THEN 'keyboard'
  WHEN 'Virtual Assistance' THEN 'headphones'
  WHEN 'Tech Support' THEN 'life-buoy'
  WHEN 'SEO' THEN 'search'
  WHEN 'Digital Marketing' THEN 'megaphone'
  WHEN 'Social Media Management' THEN 'share-2'
  WHEN 'No-Code Development' THEN 'blocks'
  -- Student Tasks
  WHEN 'Tutoring - Math' THEN 'calculator'
  WHEN 'Tutoring - Science' THEN 'flask-conical'
  WHEN 'Tutoring - English' THEN 'book-open'
  WHEN 'Tutoring - Programming' THEN 'code'
  WHEN 'Assignment Help' THEN 'file-text'
  WHEN 'Research Assistance' THEN 'search'
  WHEN 'Academic Writing' THEN 'pencil'
  WHEN 'Thesis/Dissertation Help' THEN 'graduation-cap'
  WHEN 'Presentation Design' THEN 'presentation'
  WHEN 'Proofreading & Editing' THEN 'spell-check'
  WHEN 'Translation' THEN 'languages'
  WHEN 'Transcription' THEN 'file-audio'
  WHEN 'Resume Writing' THEN 'file-user'
  WHEN 'Cover Letter Writing' THEN 'mail'
  WHEN 'Exam Preparation' THEN 'clipboard-list'
  -- Skilled Work
  WHEN 'Plumbing' THEN 'droplet'
  WHEN 'Electrical Work' THEN 'zap'
  WHEN 'Carpentry' THEN 'hammer'
  WHEN 'Painting' THEN 'paintbrush'
  WHEN 'HVAC Repair' THEN 'thermometer'
  WHEN 'Appliance Repair' THEN 'wrench'
  WHEN 'Furniture Assembly' THEN 'armchair'
  WHEN 'Moving & Packing' THEN 'package'
  WHEN 'Delivery Services' THEN 'truck'
  WHEN 'Cleaning Services' THEN 'sparkles'
  WHEN 'Gardening & Landscaping' THEN 'flower-2'
  WHEN 'Home Renovation' THEN 'construction'
  WHEN 'Welding' THEN 'flame'
  WHEN 'Auto Repair' THEN 'car'
  WHEN 'Handyman Services' THEN 'tool'
  WHEN 'Event Planning' THEN 'calendar'
  WHEN 'Catering' THEN 'utensils'
  WHEN 'DJ Services' THEN 'disc'
  WHEN 'Personal Training' THEN 'dumbbell'
  WHEN 'Cooking & Chef Services' THEN 'chef-hat'
  ELSE 'circle'
END;