
-- Redistribute skills into proper categories

-- === VIBE CODING === (AI-assisted coding tools and development)
UPDATE skills SET category = 'vibe_coding' WHERE name IN (
  'Agentic Coding',
  'AI Code Review',
  'AI Pair Programming',
  'AI-Assisted Debugging',
  'AI SaaS Development',
  'API Development',
  'Bolt.new Development',
  'Cursor AI Development',
  'GitHub Copilot',
  'Lovable Development',
  'Mobile App Development',
  'No-Code Development',
  'Replit Agent',
  'v0 by Vercel',
  'Web Development',
  'Windsurf Development',
  'Software Testing/QA',
  'DevOps',
  'Cloud Computing',
  'Database Administration',
  'Blockchain Development',
  'Game Development',
  'Natural Language to Code',
  'AI/ML Development',
  'Data Pipeline Engineering',
  'Cybersecurity'
);

-- === PROMPT ENGINEERING ===
UPDATE skills SET category = 'prompt_engineering' WHERE name IN (
  'ChatGPT Prompt Engineering',
  'Claude Prompt Engineering',
  'Chain-of-Thought Prompting',
  'Few-Shot Learning Prompts',
  'Prompt Injection Prevention',
  'Prompt Template Libraries',
  'System Prompt Design',
  'Custom GPT Development',
  'GPT-4/GPT-5 Optimization',
  'AI Persona Development',
  'DALL-E Prompting',
  'Midjourney Prompting',
  'Stable Diffusion Prompting',
  'Function Calling / Tool Use',
  'Claude API Integration',
  'Claude Artifacts',
  'OpenAI API Integration',
  'Gemini API Integration',
  'AI Ethics & Compliance',
  'AI Safety & Alignment'
);

-- === AI VIDEO === (AI video creation and editing tools)
UPDATE skills SET category = 'ai_video' WHERE name IN (
  'AI Animation',
  'AI Video Editing (CapCut)',
  'AI Video Translation',
  'AI Video Upscaling',
  'AI Voice Cloning for Video',
  'AI Lip Sync',
  'AI Motion Capture',
  'AI Shorts/Reels Creation',
  'D-ID Video Creation',
  'HeyGen Avatar Videos',
  'Kling AI',
  'Luma AI 3D/Video',
  'Pika Labs',
  'Runway ML Video',
  'Sora (OpenAI)',
  'Synthesia AI Videos',
  'Topaz Video AI',
  'AI Voice Synthesis',
  'ElevenLabs Voice Generation',
  'Voice AI (ElevenLabs)',
  'Voice AI (OpenAI Whisper)',
  'AI Sound Effects',
  'AI Audio Enhancement',
  'AI Audiobook Narration',
  'AI Music Production',
  'Suno AI Music',
  'Udio AI Music',
  'AI Podcast Editing'
);

-- === WEB DESIGN === (Design, UI/UX, visual content)
UPDATE skills SET category = 'web_design' WHERE name IN (
  'UI/UX Design',
  'Logo Design',
  'Graphic Design',
  'Illustration',
  'Motion Graphics',
  'Presentation Design',
  'Thumbnail Design',
  'AI Logo Design',
  'AI Background Removal',
  'AI Photo Editing',
  'AI Product Photography',
  'AI Concept Art',
  'AI Character Design',
  'AI 3D Modeling',
  'AI 3D Texture Generation',
  'AI Texture Generation',
  'AI Game Asset Generation',
  'DALL-E 3',
  'Midjourney Mastery',
  'Stable Diffusion XL',
  'Leonardo AI',
  'Ideogram AI',
  'Flux Image Generation',
  'ComfyUI Workflows',
  'ControlNet',
  'Inpainting & Outpainting',
  'LoRA Training',
  'Gaussian Splatting',
  'NeRF (Neural Radiance Fields)',
  'Blender AI Addons'
);
