// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcayjxyycbpnjilfgtet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjYXlqeHl5Y2JwbmppbGZndGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NzEyMzYsImV4cCI6MjA2NzM0NzIzNn0.mF2b-5Ab27i7Q88dN648QmqkvsF2ZN1cx-mk1oybkzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});